name: iOS CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, production ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: List available simulators
        run: xcrun simctl list devices available | grep iPhone
      
      - name: Build and Test
        run: |
          xcodebuild test \
            -project FoodOrderingApp/FoodOrderingApp.xcodeproj \
            -scheme FoodOrderingApp \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.5' \
            CODE_SIGNING_ALLOWED=NO
